#!/bin/bash

bold=$(tput bold)
normal=$(tput sgr0)

echo -e "${bold} Hello $USER!" &>> /home/aman/cygwin_alert.txt
echo -e "${bold} This report is generated at ${normal} $(date)" &>> /home/aman/cygwin_alert.txt
echo -e "${bold} Recent logins:: \n ${normal}$(last | head)" &>> /home/aman/cygwin_alert.txt
echo -e "${bold} Hostname:: ${normal} \n $(hostname)" &>> /home/aman/cygwin_alert.txt
echo -e "${bold} FQDN:: ${normal} \n $(hostname -f)" &>> /home/aman/cygwin_alert.txt

echo -e "${bold} ---------### Getting hadoop ecosystem info ###-----------" &>> /home/aman/cygwin_alert.txt

echo -e "${bold} ## Linux version:: ${normal} \n $(uname -r)" &>> /home/aman/cygwin_alert.txt
${bold} ${normal} $(java -version) | echo "java version::" &>> /home/aman/cygwin_alert.txt
echo -e "${bold} ## python versioninfo:: ${normal} \n $(python --version)" &>> /home/aman/cygwin_alert.txt
echo -e "${bold} ## Getting Hadoop info:: ${normal} \n $(hadoop version)" &>> /home/aman/cygwin_alert.txt



http://opensourceforu.efytimes.com/2015/07/shell-scripts-you-will-love-to-use/
http://www.tecmint.com/linux-server-health-monitoring-script/
https://bash.cyberciti.biz/monitoring/get-system-information-in-html-format/


mail -a /home/aman/cygwin_alert.txt -s "Cygwin alert" aman.mundra@hpe.com < /dev/null

